const restaurants = [
    {
      name: 'Casa Columbia',
      lat: 30.260846,
      lng: -97.714576,
      desc: 'A columbian place',
      cuisine: 'Columbian',
      yelp: 'https://www.yelp.com/biz/casa-colombia-austin-2',
    },
    {
      name: 'Usta Kababgy',
      lat: 30.365631,
      lng: -97.69501,
      desc: 'A Turkish place',
      cuisine: 'Turkish',
      yelp: 'https://www.yelp.com/biz/usta-kababgy-austin',
    },
    {
      name: "Aster's Ethiopian",
      lat: 30.287478,
      lng: -97.725037,
      desc: 'An Ethiopian place',
      cuisine: 'Ethiopian',
      yelp: 'https://www.yelp.com/biz/asters-ethiopian-restaurant-austin',
    },
    {
      name: 'Himalaya Kosheli',
      lat: 30.432962,
      lng: -97.770067,
      desc: 'A Nepali place',
      cuisine: 'Nepali',
      yelp: 'https://www.yelp.com/biz/himalaya-kosheli-austin',
    },
    {
      name: "Sassy's Vegetarian SOUL Food",
      lat: 30.264578,
      lng: -97.727277,
      desc: 'A vegetarian Soul food place',
      cuisine: 'Soul Food/Vegetarian',
      yelp: 'https://www.yelp.com/biz/sassys-vegetarian-soul-food-austin-3',
    },
  ]